# Generated by Django 5.0.2 on 2024-05-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('last_maintenance', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('specifications', models.TextField()),
            ],
        ),
    ]
